## Preprocessing

In [6]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [7]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.

application_df = application_df.drop(columns=['EIN', 'NAME'])
print(application_df)

      APPLICATION_TYPE       AFFILIATION CLASSIFICATION      USE_CASE  \
0                  T10       Independent          C1000    ProductDev
1                   T3       Independent          C2000  Preservation
2                   T5  CompanySponsored          C3000    ProductDev
3                   T3  CompanySponsored          C2000  Preservation
4                   T3       Independent          C1000     Heathcare
...                ...               ...            ...           ...
34294               T4       Independent          C1000    ProductDev
34295               T4  CompanySponsored          C3000    ProductDev
34296               T3  CompanySponsored          C2000  Preservation
34297               T5       Independent          C3000    ProductDev
34298               T3       Independent          C1000  Preservation

       ORGANIZATION  STATUS     INCOME_AMT SPECIAL_CONSIDERATIONS   ASK_AMT  \
0       Association       1              0                      N      5000
1      Co-operative       1         1-9999                      N    108590
2       Association       1              0                      N      5000
3             Trust       1    10000-24999                      N      6692
4             Trust       1  100000-499999                      N    142590
...             ...     ...            ...                    ...       ...
34294   Association       1              0                      N      5000
34295   Association       1              0                      N      5000
34296   Association       1              0                      N      5000
34297   Association       1              0                      N      5000
34298  Co-operative       1          1M-5M                      N  36500179

       IS_SUCCESSFUL
0                  1
1                  1
2                  0
3                  1
4                  1
...              ...
34294              0
34295              0
34296              0
34297              1
34298              0

[34299 rows x 10 columns]

In [8]:
# Determine the number of unique values in each column.

unique_values_per_column = application_df.nunique()
print(unique_values_per_column)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [10]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
app_value_count = application_df['APPLICATION_TYPE'].value_counts()
app_value_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [11]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace = app_value_count[app_value_count<500].index

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [12]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
class_value_count = application_df['CLASSIFICATION'].value_counts()
class_value_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [13]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
class_value_count[class_value_count>1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [14]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = class_value_count[class_value_count<1880].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [15]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
dummies_df = pd.get_dummies(application_df)
dummies_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [17]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = dummies_df["IS_SUCCESSFUL"].values
X = dummies_df.drop("IS_SUCCESSFUL",axis=1).values
# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [18]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [19]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
input_features = len(X_train_scaled[0])
hidden_layer_1 = 80
hidden_layer_2 =30
nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hidden_layer_1, activation="relu", input_dim=input_features))

# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hidden_layer_2, activation="relu"))

# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 5981 (23.36 KB)
Trainable params: 5981 (23.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [21]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

In [ ]:
# from keras.callbacks import Callback
# import os

# class WeightsSaver(Callback):

#     def __init__(self, weights_path, every_n_epochs=5):
#         self.weights_path = weights_path
#         self.every_n_epochs = every_n_epochs

#     def on_epoch_end(self, epoch, logs=None):
#         if (epoch + 1) % self.every_n_epochs == 0:
#             self.model.save_weights(os.path.join(self.weights_path, 'weights_{}.h5'.format(epoch)))

# weights_path = ''
# saver = WeightsSaver(weights_path, every_n_epochs=5)

# model.fit(X_train, y_train, callbacks=[saver])

In [23]:
model_checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath = "",
    save_freq="epoch", period = 5
   )

WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.

In [24]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled, y_train, epochs=100, callbacks=[model_checkpoint_callback] )

Epoch 1/100
804/804 [==============================] - 6s 4ms/step - loss: 0.5700 - accuracy: 0.7230
Epoch 2/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5557 - accuracy: 0.7299
Epoch 3/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5518 - accuracy: 0.7309
Epoch 4/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5503 - accuracy: 0.7314
Epoch 5/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5491 - accuracy: 0.7320
Epoch 6/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5484 - accuracy: 0.7321
Epoch 7/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5474 - accuracy: 0.7340
Epoch 8/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5472 - accuracy: 0.7319
Epoch 9/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5463 - accuracy: 0.7335
Epoch 10/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5459 - accuracy: 0.7339
Epoch 11/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5451 - accuracy: 0.7336
Epoch 12/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5440 - accuracy: 0.7337
Epoch 13/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5445 - accuracy: 0.7355
Epoch 14/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5441 - accuracy: 0.7359
Epoch 15/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5434 - accuracy: 0.7347
Epoch 16/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5439 - accuracy: 0.7347
Epoch 17/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5438 - accuracy: 0.7357
Epoch 18/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5430 - accuracy: 0.7356
Epoch 19/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5430 - accuracy: 0.7363
Epoch 20/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5427 - accuracy: 0.7361
Epoch 21/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5422 - accuracy: 0.7353
Epoch 22/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5416 - accuracy: 0.7361
Epoch 23/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5419 - accuracy: 0.7361
Epoch 24/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5419 - accuracy: 0.7362
Epoch 25/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5413 - accuracy: 0.7370
Epoch 26/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5410 - accuracy: 0.7371
Epoch 27/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5406 - accuracy: 0.7367
Epoch 28/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5407 - accuracy: 0.7355
Epoch 29/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5405 - accuracy: 0.7370
Epoch 30/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5403 - accuracy: 0.7374
Epoch 31/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5407 - accuracy: 0.7373
Epoch 32/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5401 - accuracy: 0.7369
Epoch 33/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5399 - accuracy: 0.7370
Epoch 34/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5400 - accuracy: 0.7377
Epoch 35/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5395 - accuracy: 0.7378
Epoch 36/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5391 - accuracy: 0.7380
Epoch 37/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5393 - accuracy: 0.7376
Epoch 38/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5394 - accuracy: 0.7364
Epoch 39/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5390 - accuracy: 0.7370
Epoch 40/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5391 - accuracy: 0.7375
Epoch 41/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5387 - accuracy: 0.7381
Epoch 42/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5388 - accuracy: 0.7379
Epoch 43/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5391 - accuracy: 0.7382
Epoch 44/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5383 - accuracy: 0.7376
Epoch 45/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5383 - accuracy: 0.7379
Epoch 46/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5385 - accuracy: 0.7380
Epoch 47/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5379 - accuracy: 0.7385
Epoch 48/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5383 - accuracy: 0.7382
Epoch 49/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5381 - accuracy: 0.7375
Epoch 50/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5382 - accuracy: 0.7377
Epoch 51/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5374 - accuracy: 0.7383
Epoch 52/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5377 - accuracy: 0.7393
Epoch 53/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5382 - accuracy: 0.7392
Epoch 54/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5374 - accuracy: 0.7381
Epoch 55/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5374 - accuracy: 0.7379
Epoch 56/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5373 - accuracy: 0.7399
Epoch 57/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5374 - accuracy: 0.7383
Epoch 58/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5374 - accuracy: 0.7382
Epoch 59/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5369 - accuracy: 0.7392
Epoch 60/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5370 - accuracy: 0.7392
Epoch 61/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5374 - accuracy: 0.7395
Epoch 62/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5372 - accuracy: 0.7385
Epoch 63/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5367 - accuracy: 0.7395
Epoch 64/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5367 - accuracy: 0.7394
Epoch 65/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5368 - accuracy: 0.7389
Epoch 66/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5365 - accuracy: 0.7378
Epoch 67/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5364 - accuracy: 0.7390
Epoch 68/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5365 - accuracy: 0.7395
Epoch 69/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5365 - accuracy: 0.7389
Epoch 70/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5367 - accuracy: 0.7390
Epoch 71/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5363 - accuracy: 0.7389
Epoch 72/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5364 - accuracy: 0.7387
Epoch 73/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5362 - accuracy: 0.7390
Epoch 74/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5364 - accuracy: 0.7389
Epoch 75/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5360 - accuracy: 0.7390
Epoch 76/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5362 - accuracy: 0.7393
Epoch 77/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5358 - accuracy: 0.7388
Epoch 78/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5361 - accuracy: 0.7388
Epoch 79/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5359 - accuracy: 0.7390
Epoch 80/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5361 - accuracy: 0.7391
Epoch 81/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5356 - accuracy: 0.7394
Epoch 82/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5362 - accuracy: 0.7391
Epoch 83/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5356 - accuracy: 0.7397
Epoch 84/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5355 - accuracy: 0.7389
Epoch 85/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5361 - accuracy: 0.7397
Epoch 86/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5354 - accuracy: 0.7395
Epoch 87/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5355 - accuracy: 0.7392
Epoch 88/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5361 - accuracy: 0.7393
Epoch 89/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5355 - accuracy: 0.7389
Epoch 90/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5352 - accuracy: 0.7397
Epoch 91/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5353 - accuracy: 0.7383
Epoch 92/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5354 - accuracy: 0.7400
Epoch 93/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5353 - accuracy: 0.7408
Epoch 94/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5354 - accuracy: 0.7393
Epoch 95/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5353 - accuracy: 0.7399
Epoch 96/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5350 - accuracy: 0.7397
Epoch 97/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5347 - accuracy: 0.7393
Epoch 98/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5349 - accuracy: 0.7403
Epoch 99/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5354 - accuracy: 0.7399
Epoch 100/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5351 - accuracy: 0.7401

In [25]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5587 - accuracy: 0.7293 - 674ms/epoch - 3ms/step
Loss: 0.5587164163589478, Accuracy: 0.7293294668197632

In [26]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save("AlphabetSoupCharity.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(